### ISSUE TITLE
Make plan reset at the payment date not each months

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#134]
**Describe the bug/issue**

**Comment by rishi-raj-jain** [comment]
Hey @riderx, Can you elaborate the issue and give me some direction?

**Comment by rishi-raj-jain** [comment]
@riderx Can you give me some direction the current payment flow in the code?

**Comment by tobihans** [comment]
@rishi-raj-jain I'm working on this.

**Comment by rishi-raj-jain** [comment]
Thanks, I'm dropping this one off.

**Comment by riderx** [comment]
i'm closing the bounty since this is a part of the refactor i do for stats

**Comment by rishi-raj-jain** [comment]
Hey @riderx,

can you close this one on Algora as well?
