### ISSUE TITLE
Bundle list too long and hard to choose

### ISSUE THREAD

**Issue by davidecampello** [Cap-go/capgo#201]
Hi! Really nice job with the last versions!
I want point you out that when you choose a bundle version to force in the device details page, when the list is very long is really hard to choose. I need to zoom out and click in the top border of the screen. 
Can you improve this aspect? 
Thank you!
Davide
<img width="240" alt="Screenshot 2023-03-08 alle 23 32 38" src="https://user-images.githubusercontent.com/21193922/223867346-cc33176d-e4b5-40cc-8d75-dac677a93278.png">

**Comment by riderx** [comment]
Thanks @davidecampello for the report ! 
i finally got to know why that was happen !
i made a PR to the design lib i use: https://github.com/konstaui/konsta/issues/135
 in the meantime i found a way to fix it in capgo in the last version. I let you try and you tell me if that fix you issue.
 I think a seach bar could improve even more the experience
