### ISSUE TITLE
Bundle set to multiple channel are not clear

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#255]
**Describe the bug/issue**
If a specific bundle is associated to multiple channels, the UI for the bundle itself only shows 1 of them which is confusing.

The goal is the show all of them and add an easy way to remove the link directly from the bundle page

**Comment by WcaleNieWolny** [comment]
Please note a couple of things:

A) Tests for this would be nice (we have playwright, take a look at [this](https://github.com/Cap-go/capgo/blob/development/tests/organization_system.spec.ts) and [this](https://github.com/Cap-go/capgo/blob/development/tests_backend/tests/organization/main.ts) for some details with impl)
B) Please base your changes on the [development branch](https://github.com/Cap-go/capgo/tree/development) to avoid merge conflicts

**Comment by yuvrajjsingh0** [comment]
> Please note a couple of things:
> 
> A) Tests for this would be nice (we have playwright, take a look at [this](https://github.com/Cap-go/capgo/blob/development/tests/organization_system.spec.ts) and [this](https://github.com/Cap-go/capgo/blob/development/tests_backend/tests/organization/main.ts) for some details with impl) B) Please base your changes on the [development branch](https://github.com/Cap-go/capgo/tree/development) to avoid merge conflicts

Cool, I will take care of it!
