### ISSUE TITLE
Move website to astro 

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#261]
The idea is to move from nuxt content who is currently broken to astro to keep vue componenent but have more reliable solution

**Comment by rishi-raj-jain** [comment]
Hey @riderx,

Is it about https://capgo.app/ or https://docs.capgo.app/?

**Comment by rishi-raj-jain** [comment]
If docs, I might just suggest https://mintlify.com/ that has an awesome DX and output + features.

**Comment by rishi-raj-jain** [comment]
What do you think, @riderx?

**Comment by rishi-raj-jain** [comment]
@riderx 

Can I target the docs (https://github.com/Cap-go/docs) first?

Also, do you think that the bounty shall be split into two -> one for website & one for docs?

**Comment by riderx** [comment]
The critical part is the website https://capgo.app who had a lot of SEO issue
The doc will come with another bounty, when the website is migrated

**Comment by riderx** [comment]
only [capgo.app](https://capgo.app)

[web.cargo.app](https://web.capgo.app/) is a webapp and cannot be done in astro ^^

**Comment by riderx** [comment]
So this repo : https://github.com/Cap-go/website is the only one to do

**Comment by rishi-raj-jain** [comment]
@riderx Can I get the bounty?

**Comment by riderx** [comment]
I try to understand how to give it to you :)

**Comment by rishi-raj-jain** [comment]
You can just do the below:

/tip $500 @rishi-raj-jain

See for ref: https://github.com/triggerdotdev/trigger.dev/issues/249#issuecomment-1663901898

**Comment by rishi-raj-jain** [comment]
Thank you so much, @riderx  🙏🏻

**Comment by riderx** [comment]
here is the other one : https://github.com/riderx/captime-website/issues/47
