### ISSUE TITLE
Allow delete and generate api keys

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#265]
Currently, the APIKEY are created when account is created but there are no way to roll the key if they leaked.
![CleanShot 2023-08-13 at 14 45 40@2x](https://github.com/Cap-go/capgo/assets/4084527/461a62da-a12e-49c4-bdf4-c165cf01a6a1)

a nice addition would be to be able to add key by type, delete and update key

**Comment by riderx** [comment]
Capgo have backend function only when nothing else can be done.
With a good RLS this can be done in frontend fully.

Renew a key should be after confirm alert, to prevent miss click.

**Comment by WcaleNieWolny** [comment]
Thanks a lot for you input, I am not going to close this and I am going to work on this tomorrow hopefully fixing all of the mentioned issues

**Comment by WcaleNieWolny** [comment]
Also what do you mean by "add by type" so like add a read only key? And updating the key should allow the user to type the key or just regenerate it?

**Comment by riderx** [comment]
there are 3 type of keys:
- upload
- read 
- write (all)

So when create a new one the user should show what type he wants to create.
I don't think change the type is necessary, only rolling the key.

**Comment by sravanth299** [comment]
@riderx This is the first time I am contributing to this repo. I am trying to set up using [263](https://github.com/Cap-go/capgo/pull/263). 

 supabase start
Seeding data supabase\seed.sql...
ERROR: relation "public.apps" does not exist (SQLSTATE 42P01)
Try rerunning the command with --debug to troubleshoot the error.

I am failing at the supabase setup.

**Comment by WcaleNieWolny** [comment]
I want to ask: How important it is to require `secure contexts (HTTPS or localhost)` for the API keys? I want to use the browser crypto API. I initialy used an edge function to avoid having to deal with crypto in the browser

**Comment by WcaleNieWolny** [comment]
I have implemented the regenerating on the frontend + I have added a dialog option. Please revew my changes

**Comment by WcaleNieWolny** [comment]
> there are 3 type of keys:
> 
>     * upload
> 
>     * read
> 
>     * write (all)
> 
> 
> So when create a new one the user should show what type he wants to create. I don't think change the type is necessary, only rolling the key.

There are 4 types of keys. Should I add all of them in or only the ones mentioned by you?
![image](https://github.com/Cap-go/capgo/assets/50914789/0e1e3f8a-8fda-4182-a5c9-3d0fbace662d)

**Comment by WcaleNieWolny** [comment]
> @riderx This is the first time I am contributing to this repo. I am trying to set up using [263](https://github.com/Cap-go/capgo/pull/263). 
> 
> 
> 
>  supabase start
> 
> Seeding data supabase\seed.sql...
> 
> ERROR: relation "public.apps" does not exist (SQLSTATE 42P01)
> 
> Try rerunning the command with --debug to troubleshoot the error.
> 
> 
> 
> I am failing at the supabase setup. 

You need to manually connect to Postgress and manually execute the code from schema.sql then from seed.sql
