### ISSUE TITLE
Removing bundle does not remove data from S3

### ISSUE THREAD

**Issue by WcaleNieWolny** [Cap-go/capgo#270]
Currently removing the bundle removes the bundle ONLY from supabase and keeps it in S3. I assume that this is not the intented behavior and this could be causing unnecessary S3 costs. Adding this functionality is critical for solving   https://github.com/Cap-go/capgo/issues/257

**Comment by WcaleNieWolny** [comment]
Note: This is a very complex issue that goes beyond the documented self hosted setup. I am aware that self hosting S3 is not official supported, but if this does not work on self hosted then neither does it work in production. This issue generates no errors as far as I can see, and it involves ALL of the web hooks (automatic triggers) as all of them are misconfigured

https://github.com/Cap-go/capgo/assets/50914789/c5a89090-61aa-4d44-973d-59b10d61dc99

**Comment by WcaleNieWolny** [comment]
I believe the solution to this is as follows:

A) Fix all automatic triggers so they accualy work
B) Document/add functionality to CLI to make `upload` work on self hosted setup so the community can work on S3 related issue
C) Document how to get S3 running in a sensible way, This might be difficult as edge functions are running in a seperated docker container that has no access to localhost, for now I have just exposed my local S3 server by a SSH tunnel but this is a very temporarily institution

**Comment by WcaleNieWolny** [comment]
Unless I am missing something or the webhooks are written this way on purpose (to make it harder to self host or to prevent errors from happening on the self hosted cloud functions) then this is really not great

**Comment by WcaleNieWolny** [comment]
Is it okay if I claim this in this with https://github.com/Cap-go/capgo/pull/273 ? There is still no docs for S3, but self hosting S3 requires changes in the CLI and it might break the official S3 server (see below)

![image](https://github.com/Cap-go/capgo/assets/50914789/3a6e9442-1330-432f-9a94-79b9f93fa2e1)

As far as I know these headers broke `minio` which is the most popular (as far as I know) self hosted S3 server

**Comment by riderx** [comment]
The point is to claim it with it yes :)
I think for self-hosted we will keep the supabase solution, s3 is here for cost reason for the cloud mainly

**Comment by WcaleNieWolny** [comment]
I do not think I can claim this (Unless algora is down)
![image](https://github.com/Cap-go/capgo/assets/50914789/828fe419-cf26-4519-8a6a-5c4c40bf5f63)

**Comment by riderx** [comment]
They maybe didn't expect 2 PR for 2 claim, I will do it for you

**Comment by riderx** [comment]
i contacted them for this

**Comment by WcaleNieWolny** [comment]
Thanks, but would /tip not work?

**Comment by riderx** [comment]
yes it will but i want to tell them ^^
