### ISSUE TITLE
Weekly email stats

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#277]
**Describe the bug/issue**
The idea is to do a cron job, who send to active account an email every week to give them stats about they account.
I will give the email content

**Comment by riderx** [comment]
Email content:
```md
```

**Comment by riderx** [comment]
Email content:
```md
Hello Capgo User,

We hope you're having a fantastic week! Here's your weekly dose of Capgo stats, served hot and fresh, just the way you like it!

Updates Dispatched: This week, we sent out a whopping {{ weekly_updates }} updates! That's like delivering [fun comparison]!

Updates Installed: Out of these, {{ weekly_install }} found their new homes in user devices. That's a {{ weekly_install_success }}% success rate! High five!

Oops Moments: Unfortunately, {{ weekly_fail }} updates couldn't make it and tripped on the way. But don't worry, we're already working on their band-aids!

App Openings: Your app was the star of the show, being opened {{ weekly_open }} times this week! That's more popular than [fun comparison]!

Time Spent: Users spent a total of {{ weekly_open_time }} hours on your app. That's equivalent to watching [fun comparison]!

Remember, every update is a step forward, and we're here to make sure your steps are as smooth as possible. Keep rocking the app world, and we'll be back next week with more fun facts!

Stay Updated,
Your Capgo Team
```

Here is the variable content I want to add:
```md
Updates Dispatched:

Little: "That's like delivering a cupcake to every student in a small school!"

Medium: "That's like delivering a pizza to every resident of a small town!"

Big: "That's like delivering a burger to everyone in a big city!"

Updates Installed:

Little: "That's a 90% success rate! Even cats don't land on their feet that often!"

Medium: "That's a success rate higher than the average pass rate of a tough university exam!"

Big: "That's a success rate that even the best basketball players would envy!"

App Openings:

Little: "Your app was opened more times than a popular local bakery's door!"

Medium: "Your app was more popular than the latest episode of a hit TV show!"

Big: "Your app was opened more times than a blockbuster movie on its opening weekend!"

Time Spent:

Little: "That's equivalent to watching the entire 'Finding Nemo' movie!"

Medium: "That's equivalent to watching the entire 'Lord of the Rings' trilogy!"

Big: "That's equivalent to watching the entire 'Game of Thrones' series!"
```

The email will be sent by plunk, the template is already created there, only the sentence variation will be done in code and the stats.

I can find a way to export data to have them in the seed if you need more.

**Comment by riderx** [comment]
The variable to be sent to plunk are:
{{ weekly_updates }}
{{ weekly_install }}
{{ weekly_install_success }}
{{ weekly_fail }}
{{ weekly_open }}
{{ weekly_open_time }}
This data exist in the database in raw form, you can calculate them, they should have they own table and be stored daily weekly and monthly.

For this:
{{fun_comparison}}
{{fun_comparison_2}}
{{fun_comparison_3}}
I let you propose what can be the treshold

**Comment by rishi-raj-jain** [comment]
Given that evon cancelled his attempt, I'd love to get on this.

**Comment by riderx** [comment]
Let gooo @rishi-raj-jain :)

**Comment by rishi-raj-jain** [comment]
Oh yes!

Can you show me how plunk works? Just a overall understanding with docs and links would be fine.

If possible, can you direct me to where do we expect/think the changes would be at?

**Comment by riderx** [comment]
https://docs.useplunk.com/guides/setting-up-automation
you can also see in the current code how it's used.
I already send email for plan usage

**Comment by riderx** [comment]
i'm not sure to understand your last question

**Comment by rishi-raj-jain** [comment]
@riderx 

The check of a user being is `isOnboarded`, right?

**Comment by fvckDesa** [comment]
@rishi-raj-jain are you working on it or i can take care of it?

**Comment by rishi-raj-jain** [comment]
@fvckDesa Feel free to pick this up.

**Comment by Wholesomebruh** [comment]
> The variable to be sent to plunk are:
> 
> ```
> {{ weekly_updates }}
> {{ weekly_install }}
> {{ weekly_install_success }}
> {{ weekly_fail }}
> {{ weekly_open }}
> {{ weekly_open_time }}
> ```
> 
> This data exist in the database in raw form, you can calculate them, they should have they own table and be stored daily weekly and monthly.
> 
> For this:
> 
> ```
> {{fun_comparison}}
> {{fun_comparison_2}}
> {{fun_comparison_3}}
> ```
> 
> I let you propose what can be the threshold

Hi @riderx ,
@rishi-raj-jain mentioned that @fvckDesa can work on it, I don't know why he deleted it, if you can help me with where to get the data from, I have implementation ready.
Thank You

**Comment by riderx** [comment]
For the data it's needed to write SQL function and call them from the Supabase SDK

**Comment by fvckDesa** [comment]
@Wholesomebruh I'm working on it, the bot automatically removed me after the 7th day

**Comment by fvckDesa** [comment]
@Wholesomebruh I have problem with supabase and now I can work on it, take care of it if you want

**Comment by Wholesomebruh** [comment]
It's open then , as I am figuring out supabase too. If anyone can help with that, I have implementation ready, just need the variables from database. Thanks @fvckDesa for confirming.

**Comment by WcaleNieWolny** [comment]
About this:
```That's a {{ weekly_install_success }}% success rate! High five```
This is not really worded in the best way in my option. 

Let's say that we will write something like
```
That's a success rate that even the best basketball players would envy! High five
```
it is all good, however what is the actual success rate? 90% 95%? 30%?

**Comment by WcaleNieWolny** [comment]
To confirm. We will create a new edge fn -> add cron timer in supabase for it -> from this edge fn we will get all of the contacts -> loop over them and use the [trackEvent](https://github.com/Cap-go/capgo/blob/850cb806c018988424ffa5e20d8e1ed489153a44/supabase/functions/_utils/plunk.ts#L47) function to send the email?

**Comment by WcaleNieWolny** [comment]
As for the template, you made a lot of variable related mistakes when writing it. 

`{{ weekly_install_success }}` will not work. `{{weekly_install_success}}` will work

**Comment by WcaleNieWolny** [comment]
I will do as much as I can (cron endpoint, perhaps improve wording a little bit) and when your stats impl is ready I will use that instead of the old `stats`

**Comment by WcaleNieWolny** [comment]
I am still working on this, I worked on the org system last week and also the [stats PR](https://github.com/Cap-go/capgo/pull/334) was not merged so I was unable to work on this

**Comment by WcaleNieWolny** [comment]
I suggest changing `Little: "That's a 90% success rate! Even cats don't land on their feet that often!"` to `Little: "That's above 80% success rate! Even cats don't land on their feet that often!"`

**Comment by rishi-raj-jain** [comment]
@WcaleNieWolny can i work on this

**Comment by WcaleNieWolny** [comment]
This is practically done here: https://github.com/WcaleNieWolny/capgo. I still need to test this and potentially improve the template but I had already wrote some code for this
