### ISSUE TITLE
Email API in public file

### ISSUE THREAD

**Issue by WcaleNieWolny** [Cap-go/capgo#280]
A private API key for `plunk` (email service) can be found [here](https://github.com/Cap-go/capgo/blob/9c9353cad8385ced93ae89559868886d661cb88b/supabase/functions/_utils/plunk.ts#L33)

For anyone looking to abuse this: This issue has already been fixed, the API key has already been regenerated.
![image](https://github.com/Cap-go/capgo/assets/50914789/e476073e-44ee-4aa3-ab56-f10160dce1c1)

**Comment by riderx** [comment]
Thanks a lot

**Comment by riderx** [comment]
this has been resolved
