### ISSUE TITLE
Optimize update endpoint

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#292]
Right now, update endpoint takes 2/3 sec in prod to answer, it can be reduced to less than 0.5 sec with edge functions if well done

**Comment by rishi-raj-jain** [comment]
@riderx 

By update endpoint, you're referring to supabase/functions/updates/index.ts, right?

**Comment by rishi-raj-jain** [comment]
<img width="858" alt="Screenshot 2023-08-22 at 1 22 41 AM" src="https://github.com/Cap-go/capgo/assets/46300090/0a5f7cb2-fcb5-43e0-a843-677d898c7648">

Just trying to understand, do we want to updateDevice first even if the plan isn't valid? The order of the code shall be reversed, right?

**Comment by riderx** [comment]
I think i did this to be able to keep stats of user who don't pay but use Capgo on they own

**Comment by rishi-raj-jain** [comment]
Yeah what I could think of is just cron jobs / functions that'd work in the background and won't await the whole thing to get done sequentially.

**Comment by riderx** [comment]
also interesting to read : https://blog.mansueli.com/building-a-queue-system-with-supabase-and-postgresql

**Comment by rishi-raj-jain** [comment]
@riderx 

I don't understand how https://blog.mansueli.com/building-a-queue-system-with-supabase-and-postgresql#heading-consuming-the-queue-with-supabase-edge-function kicks the job queue?

**Comment by rishi-raj-jain** [comment]
Okay I see, it adds the tasks to the tasks key.

**Comment by rishi-raj-jain** [comment]
This is open, seems like I don't have the expertise here to get this done over with asap.

**Comment by rishi-raj-jain** [comment]
@ayewo Can you take a look athis?

**Comment by ayewo** [comment]
@rishi-raj-jain thanks for the heads up. Wont be able to until I'm done with 119.

Perhaps you want to take a go at this @WcaleNieWolny ?

**Comment by WcaleNieWolny** [comment]
I would love to try this. I had a productive talk with ridex and I am currently working on this

**Comment by Ishaan29** [comment]
hey @WcaleNieWolny, @rishi-raj-jain 
I would like to give this a try, do let me know if you are currently working on it or if you are open to collaborate  🚀

**Comment by WcaleNieWolny** [comment]
Yes, i am very much working on this. I have already wrote some code as well as requested feedback for my idea here: https://github.com/Cap-go/capgo/issues/308

**Comment by WcaleNieWolny** [comment]
@Ishaan29 If you have any others ideas (other then caching) on this please let me know
