### ISSUE TITLE
Make log compute stats every min instead of on stats create

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#306]
The current way of capgo to make stats was to compute data in the stats function ( commented code )
an by calling the trigger on_log_created , this is taking too much process for big load, so a better solution is needed

**Comment by riderx** [comment]
@evonloch sorry this was very important for Capgo, since this part was not working anymore.
I made it today, now the necessary part is more about using the new data, who is stored in app_usage.
In the front charts, in the billing section, and in the postgres function who check if user has the right to do action

**Comment by evonloch** [comment]
Okay, No worries. I am cancelling my attempt.
