### ISSUE TITLE
Inconsistent stats behavior

### ISSUE THREAD

**Issue by WcaleNieWolny** [Cap-go/capgo#321]
I noticed that in the self hosted capgo ([this branch](https://github.com/WcaleNieWolny/capgo/tree/organization-system)) the stats are not always drawn in the same way. Somethimes the upper limit is set to `20` and sometimes to `15`. This is kind of random and I cannot see any explanation for this behavior.

Here is the video of this bug

https://github.com/Cap-go/capgo/assets/50914789/cf90769b-bb70-4dd1-bb54-b5d46a7046d4

I have not really touched anything and this is the default deployment. (I recently restarted the local db to match with the latest `20230815171919_base.sql` and `seed.sql`). 

I am also not sure how is it possible to have `22.04` monthly users.  

If someone can investigate this in prod that would be great

**Comment by kremedev** [comment]
https://github.com/Cap-go/capgo/blob/cd61f433e3cb1b6308344e9aef30149622e26fef/src/components/LineChartStats.vue#L76

**Comment by kremedev** [comment]
Stats should look like this, right?
![mine](https://github.com/Cap-go/capgo/assets/134702704/00bd7a79-4334-4e50-a81f-4e7d070f5aa8)

**Comment by WcaleNieWolny** [comment]
Closing, the stats impl has changed
