### ISSUE TITLE
The migration sql script is broken again

### ISSUE THREAD

**Issue by ayewo** [Cap-go/capgo#326]
I would like to rebase on top of the latest in main but unfortunately, `supabase start` is failing again on  [20230815171919_base.sql](https://github.com/Cap-go/capgo/blob/main/supabase/migrations/20230815171919_base.sql).

It's a bit frustrating as I've fixed a similar issue [before](https://github.com/Cap-go/capgo/pull/298), and would rather avoid this busy work.

Wondering how this repeated issue can be avoided using GitHub Actions?

**Comment by riderx** [comment]
We need to add automatic test !
