### ISSUE TITLE
bug: Channel overrides are broken

### ISSUE THREAD

**Issue by simonflk** [Cap-go/capgo#355]
Since some point in the last few days if I assign a device to a channel it will not receive updates.

The only way I have been able to receive updated versions is if I remove the channel override from the device which means I effectively only have a single channel right now.

Affected: iOS & Android

```
⚡️  To Native ->  CapacitorUpdater getLatest 133573232
✨  Capacitor-updater: Getting info for bundle [builtin]
✨  Capacitor-updater: Auto-update parameters: InfoObject(platform: Optional("ios"), device_id: Optional("CA64EF65-9CA4-41EF-AE84-BBD4DF0744E9"), app_id: Optional("global.arenalabs.strive"), custom_id: Optional("env:development|user:26|team:simon"), version_build: Optional("3.7.2"), version_code: Optional("3.7.2"), version_os: Optional("16.4"), version_name: Optional("builtin"), plugin_version: Optional("10.0.0"), is_emulator: Optional(true), is_prod: Optional(false), action: nil, channel: nil)
ERROR MESSAGE:  {"errorMessage":"No new version available","message":"No new version available"}
```

**Comment by mnmt7** [comment]
@riderx, can you please assign this issue to me?

**Comment by WcaleNieWolny** [comment]
@mnmt7 I am sorry, but I have submitted a PR that probably fixes this issue [here](https://github.com/Cap-go/capgo/pull/357). If you could check if this PR fixes the issue and submit a review you will sill get 20$ for that review according to the [bounty.md](https://github.com/Cap-go/capgo/blob/main/BOUNTY.md)

**Comment by simonflk** [comment]
> @mnmt7 I am sorry, but I have submitted a PR that probably fixes this issue [here](https://github.com/Cap-go/capgo/pull/357).

I tested this a few hours ago and appears fixed, thank you @WcaleNieWolny
