### ISSUE TITLE
Fix devices tab name in channel

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#361]
**Describe the bug/issue**
Currently the device tab in channel is misleading, users tend to think is this device list who use the channel where it’s the list of device who have the channel forced to it.
So default device are not concerned.

So the name should be updated to something who reflects its content

**Comment by rishi-raj-jain** [comment]
@riderx For example, you're referring to what you see on https://web.capgo.app/app/p/ee--forgr--captime/devices?

**Comment by Paythonk** [comment]
@riderx Can you explain me more specific to error .

**Comment by RANJEETJ06** [comment]
@rishi-raj-jain why is this happening can you get it ?

![Screenshot (44)](https://github.com/Cap-go/capgo/assets/121615244/6f457e30-716f-43a1-924c-61edbd1f78f3)

**Comment by rishi-raj-jain** [comment]
I believe @riderx would know more.

**Comment by RANJEETJ06** [comment]
@riderx plz tell me about this 

![Screenshot (44)](https://github.com/Cap-go/capgo/assets/121615244/670689e1-f0d3-4d70-be5c-ddde3df663e7)
