### ISSUE TITLE
Migrate from Stripe to Lemon  Squeezy

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#366]
I currently have an issue with an accountant who don't want to declare Tax in every state of the world, so I need to migrate to MOR gateway, like paddle or Lemon.

All stripe function, billing and Pay as you go should be migrated

https://www.lemonsqueezy.com/features/usage-based-billing

A guide on how to migrate should be here

**Comment by riderx** [comment]
I have a call with new accountant monday and from that i will know if i need to switch

**Comment by riderx** [comment]
Lemon !

**Comment by rajdip-b** [comment]
Hey @b4s36t4, are you still working on this? If so, can we pair up?

**Comment by b4s36t4** [comment]
Sure, will share the fork branch with you.

**Comment by b4s36t4** [comment]
@rajdip-b Please share your discord please.

**Comment by rajdip-b** [comment]
Is anyone still attempting this one? If not, I would like to take this up!

**Comment by rajdip-b** [comment]
@riderx can you give a sort of list of the features that will be impacted by this change? For example: pay-as-you-go, purchase, etc? It would really help me in establishing the scope of the change!

**Comment by WcaleNieWolny** [comment]
> @riderx can you give a sort of list of the features that will be impacted by this change? For example: pay-as-you-go, purchase, etc? It would really help me in establishing the scope of the change!

Everything would be affected. From creating the account (`on_user_create` edge fn) to handling the purchase, creating the checkout etc. Keep in mind that stripe has zero documentation in our project so you are on your own. No one ever documented how to setup stripe when self hosting capgo

**Comment by rajdip-b** [comment]
Hey @riderx, sorry, but I won't be able to finish this PR. I did face quite a few blockers (along with the fact that this was a level greater than my current skillset) in migrating the payment method. Here are some of the thing which might really help folks in taking up this issue:
- Documenting the scope of payment module: including the refs to different modules that use payment (eg: purchase, subscription)
- I noticed that there were many events that were being consumed by the backend, but I was entirely unsure about what it was supposed to do
- Some initial docs about how stripe is being used in the first place would come in really handy. For example, the `stripe_info` table in the migration can be documented a bit as to why and where it gets the data from. 
- An initial setup guide for the entire project might be really helpful.

**Comment by WcaleNieWolny** [comment]
> An initial setup guide for the entire project might be really helpful.

https://capgo.app/docs/self-hosted/local-dev/getting-started/

> Documenting the scope of payment module

Yeah, that is one of the difficulties of this PR

**Comment by riderx** [comment]
Thanks @rajdip-b for trying!
/tip $30 @rajdip-b

**Comment by rajdip-b** [comment]
> Thanks @rajdip-b for trying! /tip $30 @rajdip-b

Thanks man, much appreciated!

**Comment by tusharjindal353** [comment]
I had good experience with payment gateways.love to work on this

**Comment by bnchi** [comment]
@riderx 

I was just curious, do you have existing clients that you want to migrate from stripe to lemon squeezy or should Stripe be kept as a backwards compatible option for the current clients? 

Here's the lemon squeezy documentation on the migration : 

https://docs.lemonsqueezy.com/help/migrating/migrating-from-stripe

It doesn't need code updates.

**Comment by bnchi** [comment]
One more thing : 

Yearly Pay as you go plan with stripe doesn't seem to be working the server is giving 500 bad requests for when requesting a checkout link.

![Screen Shot 2024-01-06 at 11 54 10 AM](https://github.com/Cap-go/capgo/assets/77180905/b8b1f986-3d30-4dad-95ee-25e010569125)

cc. @riderx

**Comment by WcaleNieWolny** [comment]
@bnchi is this the case for prod capgo or a setup you hosted locally?

**Comment by WcaleNieWolny** [comment]
right, i see this is an issue with prod. I will check this and give you a status update as soon as I know more

**Comment by WcaleNieWolny** [comment]
![image](https://github.com/Cap-go/capgo/assets/50914789/be79898b-6eae-483e-bf66-b7e50c89d467)

I have no idea what this error means

**Comment by bnchi** [comment]
> ![image](https://private-user-images.githubusercontent.com/50914789/294664134-be79898b-6eae-483e-bf66-b7e50c89d467.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MzU5NzksIm5iZiI6MTcwNDUzNTY3OSwicGF0aCI6Ii81MDkxNDc4OS8yOTQ2NjQxMzQtYmU3OTg5OGItNmVhZS00ODNlLWJmNjYtYjdlNTBjODlkNDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDEwMDc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZjgzMzc2Y2NjZDg2MzgzYzNmZTExMDYzODNhNGM3YzA5MmNiMWU1YmRiZTkxYjNkZWQ3ZTlkOGY4Y2M3NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9wh7q2WggKpVYU5zSbM_b1RmaPCt2GitiAyQ3iC7_yg)
> 
> I have no idea what this error means

My guess is and I'm not sure, is that in this line here https://github.com/Cap-go/capgo/blob/main/supabase/functions/_utils/stripe.ts#L98 when you're creating a checkout link the prices that are being passed for the metered option have some issues. Maybe log the prices Ids for when this plan is chosen and double check in your Stripe portal the way of how you're structuring them.

**Comment by WcaleNieWolny** [comment]
I do not have access to stripe, you have to wait for @riderx to check

**Comment by bnchi** [comment]
It would defiantly help also if you share the Stripe plans pricing structure here so that we can migrate it over to lemon for testing purposes.

**Comment by sy425191** [comment]
This looks interesting!

I would like to /attempt #366 

will create a draft PR soon

**Comment by deepam-kapur** [comment]
Hey @tusharjindal353 are you working on this? Do you want to pair on this issue?

**Comment by Sambit003** [comment]
@riderx Should I take this Issue? or it has been done ?

**Comment by WcaleNieWolny** [comment]
@Sambit003 the issue has not been fixed by anyone - the latest person closed his attempt

**Comment by adityajideveloper** [comment]
I am working on the issue. I have closed the previous pull request because the codebase has changed since it is merged with develop branch.
Because my exams were going on, I couldn't give it time but now I am working on the same.

**Comment by riderx** [comment]
I will close this issue for now, this migration implies too many things to change, and we have others priority for now
