### ISSUE TITLE
Fix pricing display

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#376]
In the webapp the Pay as you go pricing are missing compare to landing page:
![CleanShot 2023-09-19 at 08 24 53@2x](https://github.com/Cap-go/capgo/assets/4084527/262dc09b-e5a7-4919-b26c-e8dfb6fcd6e4)
Webapp:
![CleanShot 2023-09-19 at 08 25 14@2x](https://github.com/Cap-go/capgo/assets/4084527/2ac8d1e9-3e7d-4c82-90bd-7e34c60e84fe)

The price data is available in the DB data, use it from here
Pricing are display in Euro while billed in $, so dollar should be used.

**Comment by DevGajjar28** [comment]
@riderx I get error , while running code
