### ISSUE TITLE
Display billing estimate for Pay as you go plan

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#377]
When a user is in Pay as you go, a card should appear to display is current usage and what will be the billing at the end of the cycle.
Example of Supabase one
![CleanShot 2023-09-19 at 08 29 48@2x](https://github.com/Cap-go/capgo/assets/4084527/33180992-a642-461a-a10f-cd49044dd88a)

The data is available in app_usage table with the cycle data.
It's row data, so it's require you, to do the math

**Comment by ologbonowiwi** [comment]
@riderx we should do the math with plain JS or use something like [big.js](https://github.com/MikeMcl/big.js)?

**Comment by ologbonowiwi** [comment]
@rishi-raj-jain, @neo773 is halfway to close this issue, that's why I cancelled my attempt

**Comment by rishi-raj-jain** [comment]
Oh okay okay

**Comment by rishi-raj-jain** [comment]
Thanks for informing!
