### ISSUE TITLE
Unable to delete apps from dashboard

### ISSUE THREAD

**Issue by hichemfantar** [Cap-go/capgo#379]
**Describe the bug/issue**

1. click the trash icon to delete an app
2. toast shows with error `Cannot delete app icon`
![image](https://github.com/Cap-go/capgo/assets/34947993/986187db-9696-49f5-aaa4-7039375d1598)

**Comment by riderx** [comment]
Thanks for the report i will make bounty for that !

**Comment by rishi-raj-jain** [comment]
/attempt #379

I'm already working on this.

**Comment by hichemfantar** [comment]
Any idea how long the update takes to propagate? because I'm still getting the same error.

**Comment by riderx** [comment]
@hichemfantar maybe you just need to force reload with CTRL + MAJ + R ?

**Comment by hichemfantar** [comment]
Ok now the error changed,
```
{
    "code": "57014",
    "details": null,
    "hint": null,
    "message": "canceling statement due to statement timeout"
}
```
![image](https://github.com/Cap-go/capgo/assets/34947993/ec710f47-2c6b-4103-912b-19415362606a)
