### ISSUE TITLE
Add auto deploy Supabase migration on main merge

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#381]
Currently, when merge on master I have to put myself to add migration in the prod, I would like to have that done automatic.

A documentation on how adding Supabase migration change has to be done to make dev understand how to add change and not modify wrong file

**Comment by ayusham001** [comment]
I would like to work on this:)

**Comment by ayusham001** [comment]
@riderx can you please locate in which folder I have to add the docs?
