### ISSUE TITLE
Protect Update and stats endpoint from bad actors

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#384]
![CleanShot 2023-09-19 at 19 53 37@2x](https://github.com/Cap-go/capgo/assets/4084527/2ede4391-904d-4d71-be2f-7756f98206f7)
Our redis got bloated of fake date from update enpoind.
A good thing could be to update zod check in update enpoint to be less permissive and force correct type.
And make stats endpoint to use the same logic

**Comment by rishi-raj-jain** [comment]
Might also want to see the key and evaluate if it doesn't contain any $ or {}

**Comment by riderx** [comment]
my ask is to use zod package to validate the fields, and no only the appId but all fields

**Comment by ayewo** [comment]
Ok but Zod is already being used to parse fields in the /updates endpoint but not in the /stats endpoint.

**Comment by ayewo** [comment]
Wait, the screenshot above is for the Redis keys created by the /updates endpoint, right?

Even with some Zod parsing in place, the fake data still got through … unless regex is used to check the content as I have done.

**Comment by WcaleNieWolny** [comment]
> Even with some Zod parsing in place

The parsing is not sufficient, zod just check if app is is a string

**Comment by riderx** [comment]
yes i believe it's required to add regex in zod as well, my point is to have only one way to check to make it all with zod

**Comment by ayewo** [comment]
> yes i believe it's required to add regex in zod as well, my point is to have only one way to check to make it all with zod

I've made validation more strict using Zod.

Please see commit [`6402f3c`](https://github.com/Cap-go/capgo/pull/385/commits/6402f3c111e8593a9faa07a5a89a5ae2382d5cb4).

**Comment by ayewo** [comment]
@riderx bump.
