### ISSUE TITLE
Update stats endpoint and CLI to use Supabase broadcast

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#411]
https://supabase.com/docs/guides/realtime/broadcast

Currently, the CLI use an infinite loop who fetch stats table to run the debug command.

This is not a good solution, and doesn't work with new click house integration

A better solution would be to create a channel and broadcast in it each time a log is created for this device.

Broadcast should happen only if a listener is connected. 

For that, a new table could be required.

The goal is to allow the CLI user to debug in real time they app

**Comment by 5war00p** [comment]
Proposal:
Hey @riderx, instead of subscribing to normal channel, I'm gonna directly subscribe to database changes: https://supabase.com/docs/guides/realtime/subscribing-to-database-changes
And instead of doing `while(true)` will take the changes returned from subscribed channel and call `uploadData` func

**Comment by riderx** [comment]
@5war00p this is not possible, because the CLI do not login like user but with API key.
So RLS cannot work.
And in top of that in production now we use ClickHouse so the data are not stored to supabase anymore so the solution shouldn't watch stats table, but something else.

**Comment by 5war00p** [comment]
Hm, them realtime broadcast is the one we should be looking into. In that case we need to open a channel connection on sending side and broadcast, so you are saying create a new table to track each client logs state. right?

**Comment by 5war00p** [comment]
Instead of creating a new table, we use `SELECT * FROM pg_stat_activity WHERE channel = 'my_channel'` to get all the subscribers that are connected to a particular channel, if the the rows > 0 then will broadcas the messages.

cc: @riderx

**Comment by WcaleNieWolny** [comment]
I will be attempting this. I figured out how to authenticate as a user using JWT from CLI. (How to authenticate using apikey while generating JWT) thus the 'So RLS cannot work' is no longer relevant

**Comment by riderx** [comment]
This has been fixed by using Clickhouse direct read for now with a loop
