### ISSUE TITLE
Add test for channel self endpoint

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#413]
The goal is to make this endpoint 100% tested.
For read and write.
It should check happy path and wrong scenario

**Comment by rishi-raj-jain** [comment]
@neo773 how's this going

**Comment by WcaleNieWolny** [comment]
Not to say anything tho the E2E is broken right now, you can see it  [here](https://github.com/Cap-go/github-bot/actions/runs/6495356827/job/17640151685]). A fix for those broken tests (related to devices and updates) would be nice if someone figures out how to modify the device from the testing framework

**Comment by WcaleNieWolny** [comment]
I have talked to neo, and he gave me the permission to attempt this

/attempt #413

**Comment by WcaleNieWolny** [comment]
This got in a bit of a dead lock. I had to work on capgo test bot (sort of required for this PR) and thus I was not able to work on this. As of today I am stating actually working on this
