### ISSUE TITLE
Add CI/CD step to auto deploy cloudflare worker

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#414]
**Describe the bug/issue**
We currently use a cloudflare worker here :
cloudflare_workers/loadbanlancer.js
and this worker is manually deployed each time it's modified, the goal is to make this deploy automatic on every master deploy.
To prepare the future of Capgo were stats, and update endpoint will be directly a Cloudflare worker to optimize cost.

**Comment by rishi-raj-jain** [comment]
You mean `main` deploy, right?
