### ISSUE TITLE
Add to Cloudflare worker update and stats endpoint

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#415]
Currently, Cloudflare worker is redirecting to Supabase function for update and stats endpoint.
This lead to increase the latency and cost x3.
Cloudflare worker price + Supabase worker price (2 time Cloudflare one)
So the goal is to make a script like we have for Netlify serverless function where we automatically generate the code for Cloudflare workers.
One worker should be used to reduce cost.
Bonus, a rework on the generate Netlify logic could be done to simplify the code:
https://www.npmjs.com/package/hono
could be used on every platform (Supabase function, Cloudflare, Netlify and Netlify edge) to make the code the same

**Comment by rishi-raj-jain** [comment]
Proceeding as talked with @riderx on Discord

**Comment by riderx** [comment]
seems :
https://docs.deno.com/runtime/manual/advanced/deploying_deno/cloudflare_workers could help for cloudflare worker

**Comment by rishi-raj-jain** [comment]
Waiting for Martin to test the latest update in prod

**Comment by rishi-raj-jain** [comment]
Martin verified, onto this one now

**Comment by WcaleNieWolny** [comment]
I guess that since I [create a partial solution](https://github.com/Cap-go/capgo/pull/448) I should announce that I am attempting this

/attempt #415

**Comment by riderx** [comment]
@rishi-raj-jain i made this for the work on the captime repo

**Comment by riderx** [comment]
/tip $30 @rishi-raj-jain thanks for the md file migration !
