### ISSUE TITLE
Make channel_self remove channel override if set to default

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#431]
Currently if client set himself to default it create a row in channel_override with the default channel.

This is not good and lead to overload the channel_override table.

So channel_self should be modified to don't add row if that link to the default, and remove any channel_override already present.
This has to be tested in E2E test

**Comment by WcaleNieWolny** [comment]
@rishi-raj-jain Are you working on it? I already have tests implemented for the entire `channel_self` [endpoint testing](https://github.com/Cap-go/capgo/pull/440) so adding this is very easy for me.
