### ISSUE TITLE
Make sure when bundle version is deleted it's delete from storage.

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#447]
Right now this has many edge cases not handle.
So this should be fixed, tested and having a script to look for all old storage and remove the bundle of version already deleted in the db

**Comment by WcaleNieWolny** [comment]
@mrkirthi-24 Hey, how is your progress?

Can I attempt this?

**Comment by mrkirthi-24** [comment]
@WcaleNieWolny you can go ahead

**Comment by WcaleNieWolny** [comment]
Thanks 😄

/attempt #447
