### ISSUE TITLE
Migrate update endpoint to use Cloudflare D1 

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#460]
The gols is simple:
- reduce Supabase usage and cost.
- reduce latency

Currently Capgo uses the new architecture from Dev branch who deploy the endpoint in Cloudflare workers.
But still, they call Supabase SDK and db who make it long and costly.

Since D1 is a DB at the Edge, I would like to make Capgo do a full replication of the data require for update into D1.
And then switch from Supabase SDK to a SQL ORM to get the update's data from the DB.

The data model could be optimized in D1 if require, but for i believe the dumb way is the best way.

**Comment by WcaleNieWolny** [comment]
I've put a lot of work into this and I am near to finishing this

[Here is the branch](https://github.com/WcaleNieWolny/capgo/tree/d1_database)
