### ISSUE TITLE
Request for Pull Request Template in Capgo GitHub Repository

### ISSUE THREAD

**Issue by RutamBhagat** [Cap-go/capgo#474]
I recently worked on pull request and I noticed the repository lacks a pull request template. I propose adding a pull request template to the Capgo app repository for a more structured contribution process. It will standardize contributions and streamline the review process. This will benefit both contributors and maintainers. Thank you for considering.

Here's a suggested template:

## Summary

Fixes

Depends on

## Test plan

-

## Checklist

- [ ] My code follows the code style of this project and passes `make format`.
- [ ] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

**Comment by WcaleNieWolny** [comment]
That could be nice. tho idk about the checklist. Martin does not really enforce tests in PRs (As we have only E2E tests, no unti tests). Then we have the documentation. That is also not enforces. SOMETIMES martin asks for docs if the change regards something the end user can touch (So fronted/cli). At this stage of the project we do not really have a pipeline for handling PRs per say

**Comment by WcaleNieWolny** [comment]
PR merged, closing
