### ISSUE TITLE
As Admin i don't want to see all apps in shared list

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#496]
Since the org migration, we have issue as admin we see all apps.

Admin should only see info of other user when they request help.

![CleanShot 2023-12-29 at 11 22 12@2x](https://github.com/Cap-go/capgo/assets/4084527/cf7cae38-654e-42a8-873d-a678d0a87fbd)

**Comment by rishi-raj-jain** [comment]
Chatting with Martin on Discord.

**Comment by WcaleNieWolny** [comment]
this is fixed already https://github.com/Cap-go/capgo/pull/499

**Comment by riderx** [comment]
Yes @WcaleNieWolny did the fix, we spoked in the same time and forgot to link it.
@rishi-raj-jain sorry I hope you didn’t spend too much time on it
