### ISSUE TITLE
Allow Adding a user definded Name for device on top of device ID in capgo webapp for easier debugging.

### ISSUE THREAD

**Issue by lochehong** [Cap-go/capgo#54]
**Describe the bug/issue**
currently. we can only see device ID when we are testing and looking at logs. 

i would like to suggest that we can actually add a name to the device that links the device ID so we can easily debug.

e.g.
device 

fc67184f-3ff9-4012-8412-72a9502b4384 android get 8.0.5
5E5B36DF-9BD4-4E6A-92D7-81822FC63379 ios disableAutoUpdateToMajor 8.0.5

if name is added we can see this way.

chris lo note20ultra (fc67184f-3ff9-4012-8412-72a9502b4384) android get 8.0.5
chrislo iphone (5E5B36DF-9BD4-4E6A-92D7-81822FC63379) ios disableAutoUpdateToMajor 8.0.5

**Comment by riderx** [comment]
What if the plugin allow you to set a custom ID ?
like `CapacitorUpdater.setCustomId({customId: 'chrislo'})`
And then it will be visible in the dashboard ?

**Comment by riderx** [comment]
Done in latest Capgo release, this can also be edited in the Capgo interface
![image](https://user-images.githubusercontent.com/4084527/199700791-522478f5-3e57-4a9a-aee5-ff26af5aa68e.png)

**Comment by riderx** [comment]
YOu can also search now in the device list by custom_id
