### ISSUE TITLE
Create CI step to deploy webapp to Cloudflare workers

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#540]
The goal is to stop using Netlify deploy and instead use Cloudflare worker to deploy.

It should be integrated in GitHub Actions CI in the end of build step

**Comment by ayewo** [comment]
@riderx can you assign me ?

**Comment by rishi-raj-jain** [comment]
Can I do this as well? Just wrapped this one up: https://github.com/Cap-go/website/issues/174
