### ISSUE TITLE
Cannot delete app

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#547]
**Describe the bug/issue**
As user I should be able to delete my apps

**Comment by rishi-raj-jain** [comment]
@neo773

What happened? Want to know if there's something I should be aware of.

/attempt #547

**Comment by rishi-raj-jain** [comment]
@riderx 

Can you assign me this?

**Comment by neo773** [comment]
> @neo773
> 
> What happened? Want to know if there's something I should be aware of.
> 
> /attempt #547
> 
> [Algora profile](https://console.algora.io/@/rishi-raj-jain)	Completed bounties	Tech	Active attempts	Options
> @rishi-raj-jain	   27 Capgo bounties
> + 52 bounties from 22 projects	
> JavaScript, TypeScript,
> Vue & more
> [Cancel attempt](https://console.algora.io/api/bounties/cls1y6tky000gl60huv6e1mrg/cancel-attempt)

The problem is `job_queue` doesn't have RLS and I'm not sure how you would even write one as it stores arbitrary JSON & SQL as payload.

**Comment by riderx** [comment]
@neo773 what do you mean ?

**Comment by rishi-raj-jain** [comment]
> @rishi-raj-jain please stop ask for assigning this is not how it works ^^

Hey @riderx, I'm sorry but just want to clarify that I only asked once...

**Comment by riderx** [comment]
@rishi-raj-jain sorry. I mean generally, you didn't spam.

**Comment by rishi-raj-jain** [comment]
> @rishi-raj-jain sorry. I mean generally, you didn't spam.

Thank you, and no worries at all. Just wanted to clear up.

**Comment by rishi-raj-jain** [comment]
https://github.com/Cap-go/capgo/assets/46300090/8249dc32-dca1-4814-ae27-59477fd2199e

Full error recording 👆🏻

**Comment by rishi-raj-jain** [comment]
> > @neo773
> > What happened? Want to know if there's something I should be aware of.
> > /attempt #547
> > [Algora profile](https://console.algora.io/@/rishi-raj-jain)	Completed bounties	Tech	Active attempts	Options
> > @rishi-raj-jain	   27 Capgo bounties
> > 
> > * 52 bounties from 22 projects
> >   JavaScript, TypeScript,
> >   Vue & more
> >   [Cancel attempt](https://console.algora.io/api/bounties/cls1y6tky000gl60huv6e1mrg/cancel-attempt)
> 
> The problem is `job_queue` doesn't have RLS and I'm not sure how you would even write one as it stores arbitrary JSON & SQL as payload.

I think from the error as in the recording above as `"new row violates row-level security policy for table \"job_queue\""` is what's @neo773 is referring to.

**Comment by rishi-raj-jain** [comment]
Just sharing my learning here, this error message means that we've fully restricted the table as in the code we do have RLS enabled for `job_queue`.

<img width="838" alt="Screenshot 2024-02-02 at 7 13 24 PM" src="https://github.com/Cap-go/capgo/assets/46300090/81cb910a-feab-4f14-92f0-8b26c94d6a39">
<img width="459" alt="Screenshot 2024-02-02 at 7 13 37 PM" src="https://github.com/Cap-go/capgo/assets/46300090/a619da16-9cee-4978-9826-a39b6c5edf4e">
