### ISSUE TITLE
Provide a tutorial to self-host with GitHub release.

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#607]
**Describe the bug/issue**
This should have the code created in example folder and the documentation should be created about it in website repo

**Comment by Bhavyajain21** [comment]
Can I be assigned?

**Comment by riderx** [comment]
Follow the instructions

**Comment by ezhil56x** [comment]
@riderx I am new to the repo. Looking forward to make my first contribution. Can you explain a bit more about the issue? It would be really helpful

**Comment by riderx** [comment]
Currently, when users of Capacitor-updater want to not use Capgo cloud they have many things to install, and it's a hassle.
But if users follow this doc:
https://capgo.app/docs/plugin/self-hosted/auto-update/
it's easy to create a simple server to serve basic update flow.
The idea here is to create a solution ready to go when you cannot afford Capgo cloud.
Bases on GitHub action, release and GitHub pages (to publish the endpoint)

**Comment by maelp** [comment]
what's the status on this?

**Comment by riderx** [comment]
We dont have bandwidth to tackle it for now
