### ISSUE TITLE
Front end doesn't work anymore when self hosted

### ISSUE THREAD

**Issue by patrick-mota** [Cap-go/capgo#617]
First problem I couldn't get dev. working so I had to modify "prod" keys and url in config json to make it work with self hosted supabase.

Second problem I got this in my console when trying to access front:
Uncaught (in promise) TypeError: Promise.withResolvers is not a function

Which is caused by this modification I guess:
https://github.com/Cap-go/capgo/commit/528f96c359399a81c8ef0fb1914c6323a250e788#diff-1fd1388c53b46d1754c5e9d6d1b4a94a8470642cbed080347330a9dba8bfe3f5R34

I fixed it and now I have the frontend working then I tried to copy/past the cli cmd which looks like:
bunx --yes @capgo/cli@latest init key

and got:
error: unknown option '--yes'

I tried to join discord channel listed in front menu but the invitation link doesn't work.

I don't know if the current branch is stable or if I'm doing something wrong...

Thanks for your work :)

**Comment by riderx** [comment]
Hello @patrick-mota did you run the Supabase migration?
We merged big change in Capgo for orgs system so the frontend need this changes to work :)
https://supabase.com/docs/reference/cli/supabase-migration-up

**Comment by riderx** [comment]
Can you share what link didn't worked for discord i need to check it
