### ISSUE TITLE
Refactor minUpdateVersion to follow db convention

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#684]
**Describe the bug/issue**
This field is not following the convention and should follow it.
This has to be change in CLI as well
All fields who should be changed:
- minUpdateVersion
- enableNotifications
- optForNewsletters
- legalAccepted
- disableAutoUpdateUnderNative
- enableAbTesting
- secondaryVersionPercentage
- secondVersion
- disableAutoUpdate

Migration should be written, and CLI should be updated to work with both name.
Public API should still return the old name if it was exposed

**Comment by WcaleNieWolny** [comment]
`optForNewsletters`, `enableNotifications` are stored in `auth.users` - they are hard to change without affecting users
![image](https://github.com/Cap-go/capgo/assets/50914789/7ef0144f-59ec-4566-ba95-0563f01964aa)

`legalAccepted` is never used, we can drop it

**Comment by riderx** [comment]
legalAccepted, is required for legal aspect nothing in code require it ^^

**Comment by riderx** [comment]
ok i checked the code and yes only legal is used.
optForNewsletters, enableNotifications can stay the same in auth as they are in json obj, but they have to be changed in users table
