### ISSUE TITLE
Update the charts to remove the 0 index as there is no 0 day

### ISSUE THREAD

**Issue by arendjantetteroo** [Cap-go/capgo#70]
The dashboard charts currently show a 0 as first index. This looks weird as the chart jumps up to the 1st day. 

Better to remove the 0 index and start at 1 for first day of the month.

**Comment by riderx** [comment]
Thanks @arendjantetteroo that have been fix and deployed in https://github.com/Cap-go/capgo/commit/6d298e5f8a28cfc95f471fc261704b527a12db10

**Comment by riderx** [comment]
![image](https://user-images.githubusercontent.com/4084527/202141020-4bd1038f-5ff7-4348-be1b-ca6855432660.png)
