### ISSUE TITLE
Incorrect wording on "Remove channel" confirmation dialog

### ISSUE THREAD

**Issue by simonflk** [Cap-go/capgo#73]
### Steps to reproduce:

1. Assign a channel to a device
2. Unlink the channel (Channel link > Remove)

#### Expected:
- A confirmation popup asks "Are you sure? Unlink/Cancel"

#### Outcome:
The confirmations warns that this is "not reversible" and will "delete this channel"

![image](https://user-images.githubusercontent.com/4867329/202552191-2cf1e15f-b88a-404e-b58b-1f8b326b7f84.png)

**Comment by riderx** [comment]
<img width="281" alt="CleanShot 2022-11-18 at 21 29 31@2x" src="https://user-images.githubusercontent.com/4084527/202716209-0705c401-95bb-4ef8-9506-947d6b468524.png">
i updated the message to be more clear
