### ISSUE TITLE
Migrate stripe integration to FDW and use stripe-mock

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#760]
Current stripe integration is custom-made and not really working perfectly.
The task is to migrate to stripe FWD:
https://supabase.github.io/wrappers/stripe/
And used locally: https://github.com/stripe/stripe-mock
This will make Capgo fully testable locally and in CI/CD.
The end goal here is to add tests for stripe, like create user, delete, update, add payment remove etc.
So at minima a first test showing stripe create customer has to be present.
And This test should run in CI/CD GitHub action https://dev.to/wceolin/how-to-use-stripe-mock-with-github-actions-325

**Comment by WcaleNieWolny** [comment]
> stripe-mock is stateless. Data you send on a POST request will be validated, but it will be completely ignored beyond that. It will not be reflected on the response or on any future request -- unlike the real Stripe API, which stores the information you send it. [source](https://github.com/stripe/stripe-mock/blob/master/README.md)

I fail to understand how do you intend to test the stripe API locally nor how and where do you intend to use the FDW.

**Comment by riderx** [comment]
Cannot be done
