### ISSUE TITLE
fix: Fix translation workload

### ISSUE THREAD

**Issue by WcaleNieWolny** [Cap-go/capgo#761]
Currently we don't care about translations too much. When a key stops being used it does not get removed from the translation file and when I add a new translation key I only translate it in english.

I am proposing that we write a script that will:

A) Detect and remove all keys that are NOT used
B) Translate all new keys into other languages using the [DeepL API](https://www.deepl.com/en/pro-api)

Optionally we can run this script in a CI/CD workflow for PRs and it will auto-fix and auto-commit it's changes

**Comment by riderx** [comment]
We already have both in the VS Code extension, and we cannot do A properly as all our keys are not between t(''), so last time I cleaned up we lost many used keys. 
I believe better in us improving and block us with precommit hook that magic CI/CD

**Comment by WcaleNieWolny** [comment]
I agree with the usage of VS code extension for the time being
