### ISSUE TITLE
fix margin in device table

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#795]
**Describe the bug/issue**
![CleanShot 2024-08-16 at 04 49 18@2x](https://github.com/user-attachments/assets/a86e1035-6ff4-4f9b-bce5-ef3f87697d88)

**Comment by WcaleNieWolny** [comment]
Fixed in https://github.com/Cap-go/capgo/commit/12007702a3af15820863edde3fc4655b95f29116
